name: 'Docker Build and Push'
description: 'Docker Login, Build, and Push'
inputs:
    context:
      description: 'Context for the docker build'
      default: ./
      required: false
    dockerfile:
      description: 'Dockerfile to use for the build'
      required: true
    stage:
      description: 'Stage to build'
      required: true
    arch:
      description: 'Architecture to build'
      required: true
    push:
      description: 'Push the image to DockerHub'
      required: true
    tags:
      description: 'Name of the image to build and push'
      required: false
    username:
      description: 'DockerHub username'
      required: true
    token:
      description: 'DockerHub token'
      required: true
runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Context for Buildx
      id: buildx-context
      shell: bash
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        endpoint: builders
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.arch }}
        push: ${{ inputs.push }}
        target: ${{ inputs.stage }}
        tags: ${{ inputs.image_name }}
