name: 'Get Docker Info from PR'
description: 'Get docker image name and tag'
inputs:
  repository:
    description: 'Repository name'
    required: true
  stage:
    description: 'Docker stage to build'
    required: true
  push:
    description: 'Push to DockerHub'
    required: true
outputs:
  image_name:
    description: 'Docker image name'
    value: ${{ steps.get_image_name.outputs.IMAGE_NAME }}
  tag_name:
    description: 'Docker tag name'
    value: ${{ steps.get_tag_name.outputs.TAG_NAME }}
  push:
    description: 'Push to DockerHub'
    value: ${{ steps.push_to_dockerhub.outputs.PUSH_TO_DOCKERHUB }}
runs:
  using: "composite"
  steps:
    - name: Get Image name
      id: get_image_name
      shell: bash
      run: |
        IMAGE_NAME=${{ inputs.repository }}
        IMAGE_NAME="${IMAGE_NAME//_/-}"
        if [[ ${{ inputs.stage }} == "dev_stage" ]]; 
        then
          IMAGE_NAME+=-dev
        fi
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT

    - name: Get Tag name
      id: get_tag_name
      shell: bash
      run: |
        TAG_NAME=${{ github.head_ref }}
        TAG_NAME="${TAG_NAME//\//-}"
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

    - name: Decide if we should push to DockerHub
      id: push_to_dockerhub
      shell: bash
      run: |
        if [[ ${{ inputs.push }} == "true" && 
              ${{ github.head_ref }} != "main" && 
              ${{ github.head_ref }} != "qa" && 
              ${{ github.head_ref }} != "dev" ]];
        then
          echo "PUSH_TO_DOCKERHUB=true" >> $GITHUB_OUTPUT
        else
          echo "PUSH_TO_DOCKERHUB=false" >> $GITHUB_OUTPUT
        fi
