name: 'Push PR Docker Image'
description: 'Get docker image name, tag and push it to DockerHub'
inputs:
  repository:
    description: 'Repository name'
    required: true
  context:
    description: 'Context to build'
    required: true
  file:
    description: 'Dockerfile to build'
    required: true
  arch:
    description: 'Architecture to build'
    required: true
  stage:
    description: 'Docker stage to build'
    required: true
  push:
    description: 'Push to DockerHub'
    required: true
  dockerhub_username:
    description: 'DockerHub username'
    required: true
  dockerhub_token:
    description: 'DockerHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get Image name
      id: get_image_name
      shell: bash
      run: |
        IMAGE_NAME=${{ inputs.repository }}
        IMAGE_NAME="${IMAGE_NAME//_/-}"
        if [[ ${{ inputs.stage }} == "dev_stage" ]]; 
        then
          IMAGE_NAME+=-dev
        fi
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT

    - name: Get Tag name
      id: get_tag_name
      shell: bash
      run: |
        TAG_NAME=${{ github.head_ref }}
        TAG_NAME="${TAG_NAME//\//-}"
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

    - name: Decide if we should push to DockerHub
      id: push_to_dockerhub
      shell: bash
      run: |
        if [[ ${{ inputs.push }} == "true" && 
              ${{ github.head_ref }} != "main" && 
              ${{ github.head_ref }} != "qa" && 
              ${{ github.head_ref }} != "dev" &&
              ${{ github.head_ref }} =~ UP-[0-9]+ ]];
        then
          echo "PUSH_TO_DOCKERHUB=true" >> $GITHUB_OUTPUT
        else
          echo "PUSH_TO_DOCKERHUB=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Setup Docker
      uses: umdlife/umd_workflows/setup-docker-env-action@main
      with:
        username: ${{ inputs.dockerhub_username }}
        token: ${{ inputs.dockerhub_token }}

    - name: Build and Push image
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: ${{ inputs.arch }}
        target: ${{ inputs.stage }}
        push: ${{ steps.push_to_dockerhub.outputs.PUSH_TO_DOCKERHUB }}
        tags: ${{ inputs.dockerhub_username }}/${{ steps.get_image_name.outputs.IMAGE_NAME }}:${{ steps.get_tag_name.outputs.TAG_NAME }}
