name: 'Docker Build and Push'
description: 'Docker Login, Build, and Push'
inputs:
    username:
      description: 'DockerHub username'
      required: true
    token:
      description: 'DockerHub token'
      required: true
runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Context for Buildx
      id: buildx-context
      shell: bash
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        endpoint: builders
