name: Bump Version and Release

on:
  workflow_call:
    secrets:
      PAT: 
        required: true
jobs:
  bump_version:
      runs-on: self-hosted
      steps:
      - name: Check Out Current Repo 
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          submodules: recursive
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}

      - name: Set Bump 
        run: |
          if [[ ${{ github.ref_name }} == "main" ]]; then
            echo "BUMP=major" >> $GITHUB_ENV
          elif [[ ${{ github.ref_name }} == "qa" ]]; then
            echo "BUMP=minor" >> $GITHUB_ENV
          elif [[ ${{ github.ref_name }} == "dev" ]]; then
            echo "BUMP=patch" >> $GITHUB_ENV
          fi
          npm install semver

      - name: Bump version and push tag
        # uses: anothrNick/github-tag-action@1.67.0
        uses: umdlife/umd_workflows/bump-action@feat/manual-bump
        id: autoversion
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          INITIAL_VERSION: 1.0.0
          WITH_V: true
          DEFAULT_BUMP: ${{ env.BUMP }}
          RELEASE_BRANCHES: dev,qa,main

      - name: Release Drafter
        uses: umdlife/umd_workflows/release-drafter-action@main
        if: github.ref_name == 'main' || github.ref_name == 'qa'
        with:
          name: ${{ steps.autoversion.outputs.new_tag }}
          tag: ${{ steps.autoversion.outputs.new_tag }}
          publish: true
          prerelease: ${{ github.ref_name == 'qa' }}
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
