name: Run clang-format Linter

on:
  workflow_call:
jobs:
  cpp-check:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: '.'
        extensions: 'h,c,cpp,hpp'
        clangFormatVersion: 14
        inplace: True
      continue-on-error: true

    - uses: EndBug/add-and-commit@v9.1.1
      with:
        author_name: UMLDev Clang Robot
        author_email: dev@unmanned.life
        message: 'Committing clang-format changes'

    - uses: actions/checkout@v3
      with:
        repository: umdlife/umd_workflows
        path: umd_workflows
        ref: feat/cppcheck
    
    - name: Exctract pre-commit config file
      run: |
        cp umd_workflows/.pre-commit-config.yaml ../.pre-commit-config.yaml &&
        rm -rf umd_workflows

    - run: python -m pip install pre-commit cpplint
      shell: bash
    - run: python -m pip freeze --local
      shell: bash
    - name: Run pre-commit
      run: |   
        sudo apt install -y cppcheck
    - run: pre-commit run --show-diff-on-failure --color=always --config ../.pre-commit-config.yaml --from-ref ${{ github.base_ref }} --to-ref ${{ github.head_ref }}
      shell: bash
