name: Delete Temporal Docker Image in Dockerhub

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  rebuild_docker:
    runs-on: self-hosted
    steps:
    - name: Get Repo name
      shell: bash
      run: |
        IMAGE_NAME=${{ github.event.repository.name }}
        IMAGE_NAME="${IMAGE_NAME//_/-}"
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "$IMAGE_NAME"

    - name: Get Branch name
      shell: bash
      run: |
        BRANCH_NAME=${{ github.head_ref }}
        BRANCH_NAME="${BRANCH_NAME//\//-}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "$BRANCH_NAME"

    - name: Delete Docker Image
      shell: bash
      run: |
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DOCKERHUB_USERNAME }}'", "password": "'${{ secrets.DOCKERHUB_TOKEN }}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
        curl -s  -X DELETE  -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-dev/tags/${{ env.BRANCH_NAME }}/
        curl -s  -X DELETE  -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}/tags/${{ env.BRANCH_NAME }}/
