name: Docker Build and Push
on:
  workflow_call:
    inputs:
      context:
        description: 'Context for the docker build'
        default: ./
        required: false
        type: string
      dockerfile:
        description: 'Dockerfile to use for the build'
        required: true
        type: string
      stage:
        description: 'Stage to build'
        required: true
        type: string
      arch:
        description: 'Architecture to build'
        required: true
        type: string
      push:
        description: 'Push the image to DockerHub'
        default: false
        required: false
        type: boolean
      tags:
        description: 'Name of the image to build and push'
        required: false
        type: string
    secrets:
      username:
        description: 'DockerHub username'
        required: true
      token:
        description: 'DockerHub token'
        required: true

jobs:
  build_docker:
    runs-on: self-hosted
    timeout-minutes: 1200
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.arch }}
          push: ${{ inputs.push }}
          target: ${{ inputs.stage }}
          tags: ${{ inputs.image_name }}
