name: Label PR
on:
  workflow_call:
    secrets:
      PAT:
        required: true
jobs:
  label_pr:
    runs-on: self-hosted
    steps:
      - name: Labeler
        uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.PAT }}
          configuration-path: .github/labeler.yml
