name: Label PR with branch name

on:
  workflow_call:
    secrets:
      PAT: 
        required: true
jobs:
  label_pr:
    runs-on: self-hosted
    steps:
    - name: Check Out Workflows Repo 
      uses: actions/checkout@v3
      id: checkout_repo
      with:
        repository: umdlife/umd_workflows
        ref: feat/auto-release
        token: ${{ secrets.PAT }}
        path: umd_workflows
    - name: PR Labeler
      uses: TimonVS/pr-labeler-action@v3.1.0
      with:
          configuration-path: umd_workflows/.github/pr-labeler.yml
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
