name: Rebuild Platform Docker

on:
  workflow_call:
    inputs:
      arch:
        description: 'Architecture to build'
        required: true
        type: string
      stage:
        description: 'Stage to build'
        required: true
        type: string
      push:
        description: 'Push to DockerHub'
        required: false
        type: boolean
        default: false
    secrets:
      PAT: 
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  rebuild_docker:
    runs-on: self-hosted
    steps:
    - name: Check Out Current Repo 
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT }}
        ref: ${{ github.head_ref }}

    - name: Build and push
      uses: umdlife/umd_workflows/push-pr-docker-action@main
      with:
        repository: ${{ github.event.repository.name }}
        context: ../
        file: ./docker/Dockerfile
        arch: ${{ inputs.arch }}
        stage: ${{ inputs.stage }}
        push: ${{ inputs.push }}
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
