name: Rebuild Platform Docker from Dependency

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository to build from'
        required: true
        type: string
      arch:
        description: 'Architecture to build'
        required: true
        type: string
      stage:
        description: 'Stage to build'
        required: true
        type: string
      push:
        description: 'Push to DockerHub'
        required: false
        type: boolean
        default: false
    secrets:
      PAT: 
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  rebuild_docker:
    runs-on: [self-hosted, "${{ inputs.arch }}"]
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v4
      id: checkout_repo
      with:
        repository: umdlife/${{ inputs.repository }}
        fetch-depth: '0'
        ref: ${{ github.head_ref }}
        token: ${{ secrets.PAT }}
        submodules: recursive
        path: ${{ inputs.repository }}
      continue-on-error: true
    - name: Check Out dev Repo
      if: steps.checkout_repo.outcome == 'failure'
      uses: actions/checkout@v4
      with:
        repository: umdlife/${{ inputs.repository }}
        fetch-depth: '0'
        ref: dev
        token: ${{ secrets.PAT }}
        submodules: recursive
        path: ${{ inputs.repository }}

    - name: Checkout Branch Recursive Submodules
      shell: bash
      run: |
        cd ${{ inputs.repository }}
        git submodule foreach --recursive "git checkout ${{ github.head_ref }} || :"

    - name: Build and push
      uses: umdlife/umd_workflows/push-pr-docker-action@main
      with:
        repository: ${{ inputs.repository }}
        context: ./
        file: ./${{ inputs.repository }}/docker/Dockerfile
        arch: ${{ inputs.arch }}
        stage: ${{ inputs.stage }}
        push: ${{ inputs.push }}
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
