name: Rebuild Platform Docker

on:
  workflow_call:
    inputs:
      arch:
        description: 'Architecture to build'
        required: true
        type: string
      stage:
        description: 'Stage to build'
        required: true
        type: string
    secrets:
      PAT: 
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  rebuild_docker:
    runs-on: self-hosted
    steps:
    - name: Check Out Current Repo 
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT }}
        ref: ${{ github.head_ref }}

    - name: Build Docker Image
      uses: umdlife/umd_workflows/docker-build-push-action@main
      with:
        context: ../
        dockerfile: ./docker/Dockerfile
        arch: ${{ inputs.arch }}
        stage: ${{ inputs.stage }}
        push: false
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        token: ${{ secrets.DOCKERHUB_TOKEN }}
