name: Rebuild Platform Docker

on:
  workflow_call:
    inputs:
      arch:
        description: 'Architecture to build'
        required: true
        type: string
      stage:
        description: 'Stage to build'
        required: true
        type: string
      push:
        description: 'Push to DockerHub'
        required: false
        type: boolean
        default: false
    secrets:
      PAT: 
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  rebuild_docker:
    runs-on: self-hosted
    steps:
    - name: Check Out Current Repo 
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT }}
        ref: ${{ github.head_ref }}

    - name: Get Repo name
      shell: bash
      run: |
        IMAGE_NAME=${{ github.event.repository.name }}
        IMAGE_NAME="${IMAGE_NAME//_/-}"
        if [[ ${{ inputs.stage }} == "dev_stage" ]]; 
        then
          IMAGE_NAME+=-dev
        fi
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "$IMAGE_NAME"

    - name: Get Branch name
      shell: bash
      run: |
        BRANCH_NAME=${{ github.event.head_ref }}
        BRANCH_NAME="${BRANCH_NAME//\//-}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "$BRANCH_NAME"

    - name: Setup Docker
      uses: umdlife/umd_workflows/setup-docker-env-action@main
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        token: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: ../
        no-cache: true
        file: ./docker/Dockerfile
        platforms: ${{ inputs.arch }}
        target: ${{ inputs.stage }}
        push: ${{ inputs.push }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
