name: Rebuild Platform Docker

on:
  workflow_call:
    inputs:
      arch:
        description: 'Architecture to build'
        required: true
        type: string
      stage:
        description: 'Stage to build'
        required: true
        type: string
      push:
        description: 'Push to DockerHub'
        required: false
        type: boolean
        default: false
    secrets:
      PAT: 
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  rebuild_docker:
    runs-on: self-hosted
    steps:
    - name: Check Out Current Repo 
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT }}
        ref: ${{ github.head_ref }}

    - name: Get Docker Info
      id: get_docker_info
      uses: umdlife/umd_workflows/get-docker-info-action@feat/push-on-pr
      with:
        stage: ${{ inputs.stage }}
        push: ${{ inputs.push }}

    - name: Setup Docker
      uses: umdlife/umd_workflows/setup-docker-env-action@main
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        token: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: ../
        no-cache: true
        file: ./docker/Dockerfile
        platforms: ${{ inputs.arch }}
        target: ${{ inputs.stage }}
        push: ${{ steps.get_docker_info.outputs.push }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.get_docker_info.outputs.image_name }}:${{ steps.get_docker_info.outputs.tag_name }}
